SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/Signed_8bitMul_woAddop_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkSigned_8bitMul_woAddop.v

#EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkSigned_8bitMul_woAddop
MODULE   := test_Signed_8bitMul_woAddop

include $(shell cocotb-config --makefiles)/Makefile.sim
