SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/systolic_array_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/*.v

#EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mksystolic_array
MODULE   := test_mksystolic_array

include $(shell cocotb-config --makefiles)/Makefile.sim
