SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/MAC_int32_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkMAC_int32.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkMAC_int32
MODULE   := test_MAC_int32

include $(shell cocotb-config --makefiles)/Makefile.sim
