SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/MAC_fp32_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/*.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkMAC_fp32
MODULE   := test_mkMAC_fp32

include $(shell cocotb-config --makefiles)/Makefile.sim
