//
// Generated by Bluespec Compiler, version 2021.12.1 (build fd501401)
//
// On Mon Nov  4 01:02:30 IST 2024
//
//
// Ports:
// Name                         I/O  size props
// RDY_get_A1                     O     1
// RDY_get_B1                     O     1
// RDY_get_C1                     O     1
// RDY_get_S1_or_S2               O     1
// output_MAC                     O    32
// RDY_output_MAC                 O     1
// CLK                            I     1 clock
// RST_N                          I     1 reset
// get_A1_a                       I    16
// get_B1_b                       I    16
// get_C1_c                       I    32
// get_S1_or_S2_s1_or_s2          I     1
// EN_get_A1                      I     1
// EN_get_B1                      I     1
// EN_get_C1                      I     1
// EN_get_S1_or_S2                I     1
// EN_output_MAC                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mksystolic_array(CLK,
			RST_N,

			get_A1_a,
			EN_get_A1,
			RDY_get_A1,

			get_B1_b,
			EN_get_B1,
			RDY_get_B1,

			get_C1_c,
			EN_get_C1,
			RDY_get_C1,

			get_S1_or_S2_s1_or_s2,
			EN_get_S1_or_S2,
			RDY_get_S1_or_S2,

			EN_output_MAC,
			output_MAC,
			RDY_output_MAC);
  input  CLK;
  input  RST_N;

  // action method get_A1
  input  [15 : 0] get_A1_a;
  input  EN_get_A1;
  output RDY_get_A1;

  // action method get_B1
  input  [15 : 0] get_B1_b;
  input  EN_get_B1;
  output RDY_get_B1;

  // action method get_C1
  input  [31 : 0] get_C1_c;
  input  EN_get_C1;
  output RDY_get_C1;

  // action method get_S1_or_S2
  input  get_S1_or_S2_s1_or_s2;
  input  EN_get_S1_or_S2;
  output RDY_get_S1_or_S2;

  // actionvalue method output_MAC
  input  EN_output_MAC;
  output [31 : 0] output_MAC;
  output RDY_output_MAC;

  // signals for module outputs
  wire [31 : 0] output_MAC;
  wire RDY_get_A1, RDY_get_B1, RDY_get_C1, RDY_get_S1_or_S2, RDY_output_MAC;

  // inlined wires
  wire [32 : 0] inpC1_fifo_rv_port0__write_1,
		inpC1_fifo_rv_port1__read,
		inpC1_fifo_rv_port1__write_1,
		inpC1_fifo_rv_port2__read,
		out2_fifo_rv_port1__read,
		out2_fifo_rv_port1__write_1,
		out2_fifo_rv_port2__read;
  wire [16 : 0] inpA1_fifo_rv_port0__write_1,
		inpA1_fifo_rv_port1__read,
		inpA1_fifo_rv_port1__write_1,
		inpA1_fifo_rv_port2__read,
		inpB1_fifo_rv_port1__read,
		inpB1_fifo_rv_port1__write_1,
		inpB1_fifo_rv_port2__read;
  wire [1 : 0] inpS1_fifo_rv_port0__write_1,
	       inpS1_fifo_rv_port1__read,
	       inpS1_fifo_rv_port1__write_1,
	       inpS1_fifo_rv_port2__read;

  // register inpA1_fifo_rv
  reg [16 : 0] inpA1_fifo_rv;
  wire [16 : 0] inpA1_fifo_rv_D_IN;
  wire inpA1_fifo_rv_EN;

  // register inpB1_fifo_rv
  reg [16 : 0] inpB1_fifo_rv;
  wire [16 : 0] inpB1_fifo_rv_D_IN;
  wire inpB1_fifo_rv_EN;

  // register inpC1_fifo_rv
  reg [32 : 0] inpC1_fifo_rv;
  wire [32 : 0] inpC1_fifo_rv_D_IN;
  wire inpC1_fifo_rv_EN;

  // register inpS1_fifo_rv
  reg [1 : 0] inpS1_fifo_rv;
  wire [1 : 0] inpS1_fifo_rv_D_IN;
  wire inpS1_fifo_rv_EN;

  // register out2_fifo_rv
  reg [32 : 0] out2_fifo_rv;
  wire [32 : 0] out2_fifo_rv_D_IN;
  wire out2_fifo_rv_EN;

  // ports of submodule mac_1
  wire [31 : 0] mac_1_get_C_c, mac_1_output_MAC;
  wire [15 : 0] mac_1_get_A_a, mac_1_get_B_b, mac_1_relay_A, mac_1_relay_B;
  wire mac_1_EN_get_A,
       mac_1_EN_get_B,
       mac_1_EN_get_C,
       mac_1_EN_get_S1_or_S2,
       mac_1_EN_output_MAC,
       mac_1_RDY_get_A,
       mac_1_RDY_get_C,
       mac_1_RDY_get_S1_or_S2,
       mac_1_RDY_output_MAC,
       mac_1_RDY_relay_A,
       mac_1_RDY_relay_S,
       mac_1_get_S1_or_S2_s1_or_s2,
       mac_1_relay_S;

  // ports of submodule mac_2
  wire [31 : 0] mac_2_get_C_c, mac_2_output_MAC;
  wire [15 : 0] mac_2_get_A_a, mac_2_get_B_b;
  wire mac_2_EN_get_A,
       mac_2_EN_get_B,
       mac_2_EN_get_C,
       mac_2_EN_get_S1_or_S2,
       mac_2_EN_output_MAC,
       mac_2_RDY_get_A,
       mac_2_RDY_get_C,
       mac_2_RDY_get_S1_or_S2,
       mac_2_RDY_output_MAC,
       mac_2_get_S1_or_S2_s1_or_s2;

  // rule scheduling signals
  wire CAN_FIRE_RL_start,
       CAN_FIRE_RL_start2,
       CAN_FIRE_RL_start3,
       CAN_FIRE_RL_start4,
       CAN_FIRE_get_A1,
       CAN_FIRE_get_B1,
       CAN_FIRE_get_C1,
       CAN_FIRE_get_S1_or_S2,
       CAN_FIRE_output_MAC,
       WILL_FIRE_RL_start,
       WILL_FIRE_RL_start2,
       WILL_FIRE_RL_start3,
       WILL_FIRE_RL_start4,
       WILL_FIRE_get_A1,
       WILL_FIRE_get_B1,
       WILL_FIRE_get_C1,
       WILL_FIRE_get_S1_or_S2,
       WILL_FIRE_output_MAC;

  // action method get_A1
  assign RDY_get_A1 = !inpA1_fifo_rv_port1__read[16] ;
  assign CAN_FIRE_get_A1 = !inpA1_fifo_rv_port1__read[16] ;
  assign WILL_FIRE_get_A1 = EN_get_A1 ;

  // action method get_B1
  assign RDY_get_B1 = !inpB1_fifo_rv_port1__read[16] ;
  assign CAN_FIRE_get_B1 = !inpB1_fifo_rv_port1__read[16] ;
  assign WILL_FIRE_get_B1 = EN_get_B1 ;

  // action method get_C1
  assign RDY_get_C1 = !inpC1_fifo_rv_port1__read[32] ;
  assign CAN_FIRE_get_C1 = !inpC1_fifo_rv_port1__read[32] ;
  assign WILL_FIRE_get_C1 = EN_get_C1 ;

  // action method get_S1_or_S2
  assign RDY_get_S1_or_S2 = !inpS1_fifo_rv_port1__read[1] ;
  assign CAN_FIRE_get_S1_or_S2 = !inpS1_fifo_rv_port1__read[1] ;
  assign WILL_FIRE_get_S1_or_S2 = EN_get_S1_or_S2 ;

  // actionvalue method output_MAC
  assign output_MAC = out2_fifo_rv[31:0] ;
  assign RDY_output_MAC = out2_fifo_rv[32] ;
  assign CAN_FIRE_output_MAC = out2_fifo_rv[32] ;
  assign WILL_FIRE_output_MAC = EN_output_MAC ;

  // submodule mac_1
  mkMAC_with_wrapper mac_1(.CLK(CLK),
			   .RST_N(RST_N),
			   .get_A_a(mac_1_get_A_a),
			   .get_B_b(mac_1_get_B_b),
			   .get_C_c(mac_1_get_C_c),
			   .get_S1_or_S2_s1_or_s2(mac_1_get_S1_or_S2_s1_or_s2),
			   .EN_get_A(mac_1_EN_get_A),
			   .EN_get_B(mac_1_EN_get_B),
			   .EN_get_C(mac_1_EN_get_C),
			   .EN_get_S1_or_S2(mac_1_EN_get_S1_or_S2),
			   .EN_output_MAC(mac_1_EN_output_MAC),
			   .RDY_get_A(mac_1_RDY_get_A),
			   .RDY_get_B(),
			   .RDY_get_C(mac_1_RDY_get_C),
			   .RDY_get_S1_or_S2(mac_1_RDY_get_S1_or_S2),
			   .output_MAC(mac_1_output_MAC),
			   .RDY_output_MAC(mac_1_RDY_output_MAC),
			   .relay_A(mac_1_relay_A),
			   .RDY_relay_A(mac_1_RDY_relay_A),
			   .relay_B(mac_1_relay_B),
			   .RDY_relay_B(),
			   .relay_S(mac_1_relay_S),
			   .RDY_relay_S(mac_1_RDY_relay_S));

  // submodule mac_2
  mkMAC_with_wrapper mac_2(.CLK(CLK),
			   .RST_N(RST_N),
			   .get_A_a(mac_2_get_A_a),
			   .get_B_b(mac_2_get_B_b),
			   .get_C_c(mac_2_get_C_c),
			   .get_S1_or_S2_s1_or_s2(mac_2_get_S1_or_S2_s1_or_s2),
			   .EN_get_A(mac_2_EN_get_A),
			   .EN_get_B(mac_2_EN_get_B),
			   .EN_get_C(mac_2_EN_get_C),
			   .EN_get_S1_or_S2(mac_2_EN_get_S1_or_S2),
			   .EN_output_MAC(mac_2_EN_output_MAC),
			   .RDY_get_A(mac_2_RDY_get_A),
			   .RDY_get_B(),
			   .RDY_get_C(mac_2_RDY_get_C),
			   .RDY_get_S1_or_S2(mac_2_RDY_get_S1_or_S2),
			   .output_MAC(mac_2_output_MAC),
			   .RDY_output_MAC(mac_2_RDY_output_MAC),
			   .relay_A(),
			   .RDY_relay_A(),
			   .relay_B(),
			   .RDY_relay_B(),
			   .relay_S(),
			   .RDY_relay_S());

  // rule RL_start4
  assign CAN_FIRE_RL_start4 =
	     mac_2_RDY_output_MAC && !out2_fifo_rv_port1__read[32] ;
  assign WILL_FIRE_RL_start4 = CAN_FIRE_RL_start4 ;

  // rule RL_start3
  assign CAN_FIRE_RL_start3 = mac_2_RDY_get_C && mac_1_RDY_output_MAC ;
  assign WILL_FIRE_RL_start3 = CAN_FIRE_RL_start3 ;

  // rule RL_start2
  assign CAN_FIRE_RL_start2 =
	     mac_2_RDY_get_A && mac_1_RDY_relay_S && mac_1_RDY_relay_A &&
	     mac_2_RDY_get_S1_or_S2 ;
  assign WILL_FIRE_RL_start2 = CAN_FIRE_RL_start2 ;

  // rule RL_start
  assign CAN_FIRE_RL_start =
	     inpA1_fifo_rv[16] && inpB1_fifo_rv[16] && inpC1_fifo_rv[32] &&
	     inpS1_fifo_rv[1] &&
	     mac_1_RDY_get_A &&
	     mac_1_RDY_get_C &&
	     mac_1_RDY_get_S1_or_S2 ;
  assign WILL_FIRE_RL_start = CAN_FIRE_RL_start ;

  // inlined wires
  assign inpA1_fifo_rv_port0__write_1 =
	     { 1'd0, 16'bxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign inpA1_fifo_rv_port1__read =
	     CAN_FIRE_RL_start ?
	       inpA1_fifo_rv_port0__write_1 :
	       inpA1_fifo_rv ;
  assign inpA1_fifo_rv_port1__write_1 = { 1'd1, get_A1_a } ;
  assign inpA1_fifo_rv_port2__read =
	     EN_get_A1 ?
	       inpA1_fifo_rv_port1__write_1 :
	       inpA1_fifo_rv_port1__read ;
  assign inpB1_fifo_rv_port1__read =
	     CAN_FIRE_RL_start ?
	       inpA1_fifo_rv_port0__write_1 :
	       inpB1_fifo_rv ;
  assign inpB1_fifo_rv_port1__write_1 = { 1'd1, get_B1_b } ;
  assign inpB1_fifo_rv_port2__read =
	     EN_get_B1 ?
	       inpB1_fifo_rv_port1__write_1 :
	       inpB1_fifo_rv_port1__read ;
  assign inpC1_fifo_rv_port0__write_1 =
	     { 1'd0,
	       32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  } ;
  assign inpC1_fifo_rv_port1__read =
	     CAN_FIRE_RL_start ?
	       inpC1_fifo_rv_port0__write_1 :
	       inpC1_fifo_rv ;
  assign inpC1_fifo_rv_port1__write_1 = { 1'd1, get_C1_c } ;
  assign inpC1_fifo_rv_port2__read =
	     EN_get_C1 ?
	       inpC1_fifo_rv_port1__write_1 :
	       inpC1_fifo_rv_port1__read ;
  assign inpS1_fifo_rv_port0__write_1 =
	     { 1'd0, 1'bx /* unspecified value */  } ;
  assign inpS1_fifo_rv_port1__read =
	     CAN_FIRE_RL_start ?
	       inpS1_fifo_rv_port0__write_1 :
	       inpS1_fifo_rv ;
  assign inpS1_fifo_rv_port1__write_1 = { 1'd1, get_S1_or_S2_s1_or_s2 } ;
  assign inpS1_fifo_rv_port2__read =
	     EN_get_S1_or_S2 ?
	       inpS1_fifo_rv_port1__write_1 :
	       inpS1_fifo_rv_port1__read ;
  assign out2_fifo_rv_port1__read =
	     EN_output_MAC ? inpC1_fifo_rv_port0__write_1 : out2_fifo_rv ;
  assign out2_fifo_rv_port1__write_1 = { 1'd1, mac_2_output_MAC } ;
  assign out2_fifo_rv_port2__read =
	     CAN_FIRE_RL_start4 ?
	       out2_fifo_rv_port1__write_1 :
	       out2_fifo_rv_port1__read ;

  // register inpA1_fifo_rv
  assign inpA1_fifo_rv_D_IN = inpA1_fifo_rv_port2__read ;
  assign inpA1_fifo_rv_EN = 1'b1 ;

  // register inpB1_fifo_rv
  assign inpB1_fifo_rv_D_IN = inpB1_fifo_rv_port2__read ;
  assign inpB1_fifo_rv_EN = 1'b1 ;

  // register inpC1_fifo_rv
  assign inpC1_fifo_rv_D_IN = inpC1_fifo_rv_port2__read ;
  assign inpC1_fifo_rv_EN = 1'b1 ;

  // register inpS1_fifo_rv
  assign inpS1_fifo_rv_D_IN = inpS1_fifo_rv_port2__read ;
  assign inpS1_fifo_rv_EN = 1'b1 ;

  // register out2_fifo_rv
  assign out2_fifo_rv_D_IN = out2_fifo_rv_port2__read ;
  assign out2_fifo_rv_EN = 1'b1 ;

  // submodule mac_1
  assign mac_1_get_A_a = inpA1_fifo_rv[15:0] ;
  assign mac_1_get_B_b = inpB1_fifo_rv[15:0] ;
  assign mac_1_get_C_c = inpC1_fifo_rv[31:0] ;
  assign mac_1_get_S1_or_S2_s1_or_s2 = inpS1_fifo_rv[0] ;
  assign mac_1_EN_get_A = CAN_FIRE_RL_start ;
  assign mac_1_EN_get_B = CAN_FIRE_RL_start ;
  assign mac_1_EN_get_C = CAN_FIRE_RL_start ;
  assign mac_1_EN_get_S1_or_S2 = CAN_FIRE_RL_start ;
  assign mac_1_EN_output_MAC = CAN_FIRE_RL_start3 ;

  // submodule mac_2
  assign mac_2_get_A_a = mac_1_relay_A ;
  assign mac_2_get_B_b = mac_1_relay_B ;
  assign mac_2_get_C_c = mac_1_output_MAC ;
  assign mac_2_get_S1_or_S2_s1_or_s2 = mac_1_relay_S ;
  assign mac_2_EN_get_A = CAN_FIRE_RL_start2 ;
  assign mac_2_EN_get_B = CAN_FIRE_RL_start2 ;
  assign mac_2_EN_get_C = CAN_FIRE_RL_start3 ;
  assign mac_2_EN_get_S1_or_S2 = CAN_FIRE_RL_start2 ;
  assign mac_2_EN_output_MAC = CAN_FIRE_RL_start4 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        inpA1_fifo_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0, 16'bxxxxxxxxxxxxxxxx /* unspecified value */  };
	inpB1_fifo_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0, 16'bxxxxxxxxxxxxxxxx /* unspecified value */  };
	inpC1_fifo_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
	inpS1_fifo_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0, 1'bx /* unspecified value */  };
	out2_fifo_rv <= `BSV_ASSIGNMENT_DELAY
	    { 1'd0,
	      32'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx /* unspecified value */  };
      end
    else
      begin
        if (inpA1_fifo_rv_EN)
	  inpA1_fifo_rv <= `BSV_ASSIGNMENT_DELAY inpA1_fifo_rv_D_IN;
	if (inpB1_fifo_rv_EN)
	  inpB1_fifo_rv <= `BSV_ASSIGNMENT_DELAY inpB1_fifo_rv_D_IN;
	if (inpC1_fifo_rv_EN)
	  inpC1_fifo_rv <= `BSV_ASSIGNMENT_DELAY inpC1_fifo_rv_D_IN;
	if (inpS1_fifo_rv_EN)
	  inpS1_fifo_rv <= `BSV_ASSIGNMENT_DELAY inpS1_fifo_rv_D_IN;
	if (out2_fifo_rv_EN)
	  out2_fifo_rv <= `BSV_ASSIGNMENT_DELAY out2_fifo_rv_D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    inpA1_fifo_rv = 17'h0AAAA;
    inpB1_fifo_rv = 17'h0AAAA;
    inpC1_fifo_rv = 33'h0AAAAAAAA;
    inpS1_fifo_rv = 2'h2;
    out2_fifo_rv = 33'h0AAAAAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mksystolic_array

