SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/Signed_8bitMul_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkSigned_8bitMul.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkSigned_8bitMul
MODULE   := test_Signed_8bitMul

include $(shell cocotb-config --makefiles)/Makefile.sim
