SIM ?= verilator
TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

export PYTHONPATH:=$(PWD)/fp32_add_verif:$(PYTHONPATH)

VERILOG_SOURCES=$(PWD)/verilog/mkfp32_add.v

EXTRA_ARGS = --trace --trace-structs

TOPLEVEL = mkfp32_add
MODULE   := test_mkfp32_add

include $(shell cocotb-config --makefiles)/Makefile.sim
